repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 25.1.0
    hooks:
      - id: black
        language_version: python3.13
  - repo: https://github.com/pycqa/flake8
    rev: '7.1.2'
    hooks:
      - id: flake8
        args: [
          '--max-line-length=95',
          '--extend-select=B950',
          '--extend-ignore=E203,E501,E701',
          '--exclude=.venv,venv'
        ]
  - repo: local
    hooks:
      - id: commit-msg
        name: Commit message check
        entry: .git/hooks/commit-msg
        language: system
        stages: [commit-msg]
