# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.11-slim

# Prevent Python from writing pyc files to disc
ENV PYTHONDONTWRITEBYTECODE=1

# Prevent Python from buffering stdout and stderr
ENV PYTHONUNBUFFERED=1

WORKDIR /app

# Copy requirements and project files
COPY pyproject.toml ./
COPY README.md ./
COPY malloryai/ ./malloryai/
COPY scripts/ ./scripts/
COPY uv.lock ./

# Install build dependencies and project in editable mode
RUN pip install --upgrade pip setuptools wheel && \
    pip install -e . --no-cache-dir

# Expose port if needed (not specified, MCP servers usually use stdio)

# Command to run the MCP server
CMD ["python", "-m", "malloryai.mcp.app"]
